export const typeToCategoryMap = {
  Accessories: "Accessories",
  "Accessories Set": "accessories_set",
  Bowls: "Bowls",
  "Bowl & Lid": "bowl_lid",
  "Cup & Saucer": "cup_saucers",
  "Bowls Set": "bowls_set",
  "Cups / Mugs": "cups",
  "Cups / Mugs Set": "cups_set",
  Plates: "Plates",
  "Plates Set": "plates_set",
  Platter: "platter",
  "Platter Sets": "platter_sets",
  Table: "table",
  "Table Linens": "tablinen",
  "Table Linens Set": "table_linens_set",
  "Table Settings": "table_settings",
  Vases: "vases",
  "Vases Set": "vases_set",
  "Candle Stand": "candlestand",
  "Candle Stand Set": "candle_stand_set",
  Trinket: "trinket",
  "Trinket Set": "trinket_set",
  "Tissue Box": "tissuebox",
  Cutlery: "cutlery",
  Box: "boxes",
  "Candle Kit": "candlekits",
  Etchings: "etchings",
  Foam: "foamcuts",
  Wax: "wax",
  // "Bags": "bags",
  // "Stainless Steel": "stainless_steel",
  // "Envelopes": "envelopes",
  // "Ribbons": "ribbons"
};
